name: quantx_v49
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pandas=2.1.1
  - numpy=1.26.4
  - matplotlib=3.8.0
  - seaborn=0.12.2
  - jupyter=1.0.0
  - quantstats=0.0.60
  - scipy=1.11.3
  - pip
  - pip:
      - yfinance==0.2.43
      - pdfkit==1.0.0
      - tqdm==4.66.1
      - joblib==1.3.2
      - PyYAML==6.0.2